# Bun configuration file
# https://bun.sh/docs/runtime/bunfig

[install]
# Use exact versions for package installations
exact = false

# Install peer dependencies automatically
peer = true

[install.lockfile]
# Save lockfile after install
save = true

# Print the lockfile to stdout
# print = false
