# Bun configuration file
# https://bun.sh/docs/runtime/bunfig

[install]
# Use exact versions for package installations
exact = false

# Install peer dependencies automatically
peer = true

# Optional: Configure package manager behavior
[install.cache]
# Use a global cache for faster installs
dir = "~/.bun/install/cache"

[install.lockfile]
# Save lockfile after install
save = true

# Print the lockfile to stdout
print = false
